on: [push]

jobs:
  message:
    runs-on: ubuntu-latest
    name: Encouraging message
    steps:
    - name: action step
      id: message
      uses: phisv/crispy-octo-spork@master
      with:
        user: 'StressCal'
    - name: output time
      run: echo "The time was ${{ steps.message.outputs.time }}"
